package com.transit.ticketing.contracts;

public enum EventType {
    USER_REGISTERED, FARE_ACCOUNT_CREATED, ACCOUNT_FUNDED, FARE_MEDIA_LINKED,
    TAP_RECEIVED, TAP_ACCEPTED, TAP_REJECTED,
    JOURNEY_STARTED, JOURNEY_COMPLETED,
    FARE_CALCULATED, FARE_DEBITED, FARE_DEBIT_FAILED, LEDGER_ENTRY_POSTED,
    DEVICE_REGISTERED, DEVICE_HEARTBEAT_REPORTED, DEVICE_STATUS_CHANGED,
    DEVICE_WARNING_REPORTED, DEVICE_FAULT_REPORTED, DEVICE_REBOOTED,
    DEVICE_CONFIGURATION_CHANGED, DEVICE_OFFLINE_DETECTED, DEVICE_RECOVERED,
    VEHICLE_ARRIVAL_OBSERVED, VEHICLE_ARRIVAL_PREDICTED,
    SERVICE_DELAY_OBSERVED, SERVICE_DELAY_PREDICTED,
    PASSENGER_FLOW_AGGREGATED, PASSENGER_DEMAND_OBSERVED, PASSENGER_DEMAND_PREDICTED,
    DEVICE_HEALTH_FEATURES_AGGREGATED, DEVICE_ANOMALY_DETECTED,
    DEVICE_FAILURE_RISK_PREDICTED, DEVICE_MAINTENANCE_REQUESTED, DEVICE_MAINTENANCE_COMPLETED
}
